### ISSUE TITLE
Suggestion: Hotkeys

### ISSUE THREAD

**Issue by Phlarx** [skybaks/tm-presetsandsharing#1]
Add configurable hotkeys to each preset. If two presets have the same hotkey, they both will be applied when the hotkey is pressed.

Might be good to prevent duplicate hotkeys for multiple presets affecting the same plugin, however.

Example use case:
A "COTD" hotkey might hide most plugins
A "RPG" hotkey might show a CP counter and a timer
A "Hunting" hotkey might show a bunch of Dashboard things

**Comment by skybaks** [comment]
Thats a good idea, thanks! I hadnt thought about the restriction of a hotkey to one preset per plugin but that makes a lot of sense.

Grouping multiple plugin presets to be executed together brings to mind the idea of a "Loadout". I am going to have to think about the best way to implement that functionality into the plugin without adding too much configuration complexity for a standard user. I do really like the sound of that, though.
